AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  buggy-api

Globals:
  Function:
    Timeout: 10

Resources:
  BuggyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'*'"
        AllowCredentials: "'*'"
      MethodSettings:
        - CachingEnabled: false
          HttpMethod: "*"
          ResourcePath: "/*"
          ThrottlingRateLimit: 3
          ThrottlingBurstLimit: 3
      GatewayResponses:
        DEFAULT_4xx:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5xx:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
  BuggyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: buggy-api/api
      Handler: buggy-api
      Runtime: go1.x
      Tracing: Active
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:Batch*
              Resource:
                - Fn::ImportValue: DataStack-data-table-arn
                - !Join
                  - ""
                  - - Fn::ImportValue: DataStack-data-table-arn
                    - "/index/*"
            - Effect: "Allow"
              Action:
                - cognito-idp:AdminInitiateAuth
                - cognito-idp:AdminConfirmSignUp
                - cognito-idp:ListUsers
                - cognito-idp:SignUp
                - cognito-idp:ChangePassword
                - cognito-idp:AdminDisableUser
                - cognito-idp:AdminEnableUser
                - cognito-idp:AdminDeleteUser
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminSetUserPassword
              Resource:
                - !Join
                  - ""
                  - - Fn::Sub: "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/"
                    - Fn::ImportValue: AuthStack-user-pool-id
      Events:
        CatchAllGet:
          Type: Api
          Properties:
            RestApiId: !Ref BuggyApi
            Path: /{thepath+}
            Method: GET
        CatchAllPost:
          Type: Api
          Properties:
            RestApiId: !Ref BuggyApi
            Path: /{thepath+}
            Method: POST
        CatchAllPut:
          Type: Api
          Properties:
            RestApiId: !Ref BuggyApi
            Path: /{thepath+}
            Method: PUT
        CatchAllDelete:
          Type: Api
          Properties:
            RestApiId: !Ref BuggyApi
            Path: /{thepath+}
            Method: DELETE
      Environment:
        Variables:
          DATA_TABLE_NAME:
            Fn::ImportValue: DataStack-data-table-name
          COGNITO_POOL_ID:
            Fn::ImportValue: AuthStack-user-pool-id
          COGNITO_POOL_CLIENT_ID:
            Fn::ImportValue: AuthStack-user-pool-client-id

  # Alarms
  BuggyApiFunctionsAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: andrey.kotsar@gmail.com
          Protocol: email
      TopicName: BuggyApiFunctionAlarms

  BuggyApiLambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 60
      EvaluationPeriods: 3
      DatapointsToAlarm: 1
      Namespace: AWS/Lambda
      MetricName: Invocations
      Statistic: Sum
      Threshold: 50
      TreatMissingData: missing
      AlarmActions:
        - !Ref BuggyApiFunctionsAlarmsTopic

  BuggyApiDailyLambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaDailyInvocationsAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 86400 # 1 day
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Namespace: AWS/Lambda
      MetricName: Invocations
      Statistic: Sum
      Threshold: 1000
      TreatMissingData: missing
      AlarmActions:
        - !Ref BuggyApiFunctionsAlarmsTopic

Outputs:
  BuggyApiAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${BuggyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  BuggyApiFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt BuggyApiFunction.Arn
  BuggyApiFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BuggyApiFunctionRole.Arn
